[build.environment]
  NODE_VERSION = "22.13.1"
  NPM_FLAGS = "--version" # prevent Netlify npm install
[build]
  base = "00-set-interval-demo/01-iteration-two-react-ts/"
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store --frozen-lockfile"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."
[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200